train_dataset: tiered-imagenet
train_dataset_args: {split: train, augment: resize}
# val_dataset: tiered-imagenet
# val_dataset_args: {split: val}
fs_dataset: tiered-imagenet
fs_dataset_args: {split: test}
eval_fs_epoch: 10

model: classifier
model_args:
    encoder: convnet4_128
    encoder_args: {}
    classifier: linear-classifier
    classifier_args: {n_classes: 351}

batch_size: 128
max_epoch: 240 #120
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4 , milestones: [40, 80, 120, 160, 200]}
save_epoch: 10
visualize_datasets: False
