train_dataset: mini-imagenet
train_dataset_args: {split: train} #, augment: crop}
val_dataset: mini-imagenet
val_dataset_args: {split: train}
fs_dataset: mini-imagenet
fs_dataset_args: {split: test}
eval_fs_epoch: 10

model: classifier
model_args:
    encoder: convnet4_128
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 64}

batch_size: 128
max_epoch: 120
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4 } #, milestones: [90,180,270]}

save_epoch: 10
visualize_datasets: False
